# Generated by Django 4.0.3 on 2022-04-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_code_snippet_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
