# Generated by Django 4.0.3 on 2022-03-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='handle',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
