# Generated by Django 4.0.3 on 2022-03-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
