# Generated by Django 4.0.3 on 2022-04-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customuser_bio_customuser_company_customuser_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'A user with this email already exists.'}, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
