# Generated by Django 4.0.3 on 2022-04-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='handle',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with this handle already exists.'}, max_length=100, null=True, unique=True),
        ),
    ]
