# Generated by Django 4.0.3 on 2022-05-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_remove_client_receiver_remove_client_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='room',
            new_name='channel_name',
        ),
    ]
