# Generated by Django 4.0.3 on 2022-03-31 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='icon',
            new_name='snippet',
        ),
    ]
