# Generated by Django 4.0.3 on 2022-04-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_alter_setting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='theme',
            field=models.CharField(default='dark', max_length=10),
        ),
    ]
