# Generated by Django 4.0.3 on 2022-04-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_alter_setting_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='preferred_language',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
