# Generated by Django 4.0.3 on 2022-05-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='avatar',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
