# Generated by Django 4.0.3 on 2022-04-17 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('author', models.CharField(blank=True, max_length=250, null=True)),
                ('upvotes', models.IntegerField(blank=True, default=0, null=True)),
                ('logo', models.URLField(blank=True, max_length=350, null=True)),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True)),
                ('snippet', models.TextField(blank=True, max_length=600, null=True)),
                ('slug', models.TextField(blank=True, max_length=300, null=True)),
                ('details_url', models.URLField(blank=True, max_length=400, null=True)),
                ('author_pic', models.URLField(blank=True, max_length=400, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('published_date', models.CharField(blank=True, max_length=100, null=True)),
                ('min_to_read', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
