# Generated by Django 4.0.3 on 2022-05-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_post_fn_post_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image_fn',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
