# Generated by Django 4.0.3 on 2022-04-29 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devtrove_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtrovepost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_devtrove_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
