# Generated by Django 4.0.3 on 2022-04-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtrove_post', '0002_alter_devtrovepost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='devtrovepost',
            name='file_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='devtrovepost',
            name='filename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
