# Generated by Django 4.0.3 on 2022-04-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtrove_post', '0003_devtrovepost_file_url_devtrovepost_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devtrovepost',
            old_name='file_url',
            new_name='cover_filename',
        ),
        migrations.RenameField(
            model_name='devtrovepost',
            old_name='filename',
            new_name='cover_url',
        ),
        migrations.AddField(
            model_name='devtrovepost',
            name='post_filename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='devtrovepost',
            name='post_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
