# Generated by Django 4.0.3 on 2022-04-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtrove_post', '0004_rename_file_url_devtrovepost_cover_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devtrovepost',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
