# Generated by Django 4.0.3 on 2022-04-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='details_url',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
    ]
