# Generated by Django 4.0.3 on 2022-05-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_type_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
