# Generated by Django 4.0.3 on 2022-05-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_fn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
