# Generated by Django 4.0.3 on 2022-04-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_min_to_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
