# Generated by Django 4.0.3 on 2022-04-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_cover_image_alter_post_details_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
