# Generated by Django 4.0.3 on 2022-04-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_author_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
